version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    command: uvicorn api.main:app --reload --port 8090 --host 0.0.0.0
  jupyter:
    build: .
    volumes:
      - .:/app
    ports:
      - "8089:8089"
    command: bash -c "cd /app & jupyter notebook --no-browser --port 8089 --allow-root --ip 0.0.0.0"